-- MySQL Script generated by MySQL Workbench
-- Tue Sep 28 18:44:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cudatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cudatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cudatabase` DEFAULT CHARACTER SET utf8 ;


-- -----------------------------------------------------
-- Table `cudatabase`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cudatabase`.`user` (
  `cd_id` INT NOT NULL,
  `ds_name` VARCHAR(45) NULL,
  `ds_last_name` VARCHAR(45) NULL,
  `ds_email` VARCHAR(45) NULL,
  `ds_password` VARCHAR(45) NULL,
  `ds_phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`cd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cudatabase`.`Unit_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cudatabase`.`Unit_config` (
  `user_cd_id` INT NOT NULL,
  `ds_lenght` VARCHAR(45) NULL,
  `ds_pressure` VARCHAR(45) NULL,
  `ds_temperature` VARCHAR(45) NULL,
  PRIMARY KEY (`user_cd_id`),
  CONSTRAINT `fk_Unit_config_user`
    FOREIGN KEY (`user_cd_id`)
    REFERENCES `cudatabase`.`user` (`cd_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO user VALUES
    (1, 'Raul', 'Medrano', 'raumed12@gmail.com', '123456','04249696528' ),
    (2, 'Alberto', 'Perez', 'aperez@gmail.com', '456789','04249696528'),
    (3, 'Daniel', 'Gonzales', 'dgonzales@gmail.com', '123789', '04249696528');

INSERT INTO Unit_config VALUES
    (1, 'm', 'PSI', 'C' ),
    (2, 'Km', 'mca', 'K');